### ISSUE TITLE
下载编译通过了，但是运行报错

### ISSUE THREAD

**Issue by cngkqy** [Jude95/Fishing#2]
你好，下载编译通过了，但是运行报错

```
                                                            java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                at android.view.ViewGroup.addViewInner(ViewGroup.java:4066)
                                                                at android.view.ViewGroup.addView(ViewGroup.java:3916)
                                                                at android.view.ViewGroup.addView(ViewGroup.java:3857)
                                                                at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:585)
                                                                at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6254)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6212)
                                                                at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6200)
                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:546)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                at android.view.View.layout(View.java:16001)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:518
```

**Comment by cngkqy** [comment]
我本来想研究研究mvp架构写的程序的，结果运行不了，麻烦能给看看么，谢谢。
